### ISSUE TITLE
Bug fichiers Videos explorer

### ISSUE THREAD

**Issue by Crappy** [MediaMotionCommunity/MediaMotion#25]
J'ai une traceback comme ça par fichier (10 erreurs si 10 videos dans le dossier) : 

InvalidOperationException: Operation is not valid due to the current state of the object
System.Linq.Enumerable.First[KeyValuePair`2] (IEnumerable`1 source, System.Func`2 predicate, Fallback fallback)
System.Linq.Enumerable.First[KeyValuePair`2] (IEnumerable`1 source, System.Func`2 predicate)
MediaMotion.Core.Services.ResourcesManager.Container.ResourceContainer`1[UnityEngine.Material].Get (System.String name) (at Assets/Project/Core/Services/ResourcesManager/Container/ResourceContainer.cs:46)
MediaMotion.Modules.Explorer.Controllers.ElementController.Init (IResourceManagerService resourceManagerService) (at Assets/Project/Modules/Explorer/Controllers/ElementController.cs:46)
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:222)
Rethrow as TargetInvocationException: Exception has been thrown by the target of an invocation.
System.Reflection.MonoMethod.Invoke (System.Object obj, BindingFlags invokeAttr, System.Reflection.Binder binder, System.Object[] parameters, System.Globalization.CultureInfo culture) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MonoMethod.cs:232)
System.Reflection.MethodBase.Invoke (System.Object obj, System.Object[] parameters) (at /Users/builduser/buildslave/mono-runtime-and-classlibs/build/mcs/class/corlib/System.Reflection/MethodBase.cs:115)
MediaMotion.Core.Models.Scripts.BaseUnityScript`1[Script].Start () (at Assets/Project/Core/Models/Scripts/BaseUnityScript.cs:32)

**Comment by zitch** [comment]
Fixed in commit f9fa524
